lib/smarthood_web/router.ex
defmodule SmarthoodWeb.Router do
  use SmarthoodWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Pjax.Plugs.Pjax)
  end

  # pipeline :browser_auth do
  #   plug Guardian.Plug.VerifySession
  #   plug Guardian.Plug.EnsureAuthenticated, handler: Smarthood.AuthErrorHandler
  #   plug Guardian.Plug.LoadResource, allow_blank: true
  #   plug Smarthood.CurrentUser
  # end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end
  pipeline :browser_session do
    plug(Smarthood.Guardian.AuthPipeline.Browser)
    plug(Smarthood.Auth.CurrentUser)
  end

  pipeline :login_required do
    plug(Smarthood.Guardian.AuthPipeline.Authenticate)
  end

  # pipeline :authorize_admin do
  #   plug Smarthood.Guardian.AuthPipeline.Authenticate
  #   plug Smarthood.Auth.Authorize, :admin
  # end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(Smarthood.Guardian.AuthPipeline.JSON)
  end

  scope "/auth", SmarthoodWeb do
    pipe_through([:browser, :browser_session])

    get("/:provider", AuthController, :new)
    get("/:provider/callback", AuthController, :callback)
    post("/identity/callback", AuthController, :identity_callback)
    delete("/delete", AuthController, :delete)
  end

  scope "/", SmarthoodWeb do
    pipe_through([:browser, :browser_session])

    resources("/users", UserController, only: [:new, :create])
  end

  scope "/", SmarthoodWeb do
    # Use the default browser stack
    pipe_through([:browser, :browser_session, :login_required])

    get("/", PageController, :index)
    resources("/users", UserController, except: [:new, :create])
    resources("/roles", RoleController)

    # resources "/organizations", OrganizationController do
    resources "/organizations", OrganizationController do
      resources("/domains", DomainController)
      resources("/work_status_types", WorkStatusTypeController)
      resources("/spreadsheets", SpreadsheetController)
      resources("/to_dos", ToDoController)
    end

    resources "/communities", CommunityController do
      resources("/users", UserController) do
        get("/join", UserController, :add_user_to_community, as: :join)
        get("/unjoin", UserController, :remove_user_from_community, as: :unjoin)
      end
    end
    resources "/sites", SiteController do
      resources "/houses", HouseController
    end

    resources "/houses", HouseController

    resources "/to_dos", ToDoController, only: [], as: :to_do do
      resources("/to_do_users", ToDoUserController, as: :users)
    end

    resources "/teams", TeamController do
      get("/add_users", TeamController, :add_users, as: :add_users)
      get("/remove_users", TeamController, :remove_users, as: :remove_users)
      get("/set_as_moderator", TeamController, :set_as_moderator, as: :set_as_moderator)
      get("/set_as_member", TeamController, :set_as_member, as: :set_as_member)
    end

    post("/photos/upload", PhotoController, :upload)

    resources "/work_statuses", WorkStatusController do
      resources("/key_result_areas", KeyResultAreaController)
      resources("/comments", CommentController)
    end

    get("/team_work_statuses", WorkStatusController, :team_work_statuses, as: :team_work_statuses)
    resources("/tasks", TaskController)

    get(
      "/export_to_do_to_tasks",
      TaskController,
      :export_to_do_to_tasks,
      as: :export_to_do_to_tasks
    )

    get("/team_to_dos", ToDoController, :team_to_dos, as: :team_to_dos)
  end

  # Other scopes may use custom stacks.
  # scope "/api", SmarthoodWeb do
  #   pipe_through :api
  # end
end

lib/smarthood/communities/site.ex
defmodule Smarthood.Communities.Site do
  use Ecto.Schema
  import Ecto.Changeset
  alias Smarthood.Communities.Site


  schema "sites" do
    field :corner, :boolean, default: false
    field :cross, :string
    field :direction_facing, :string
    field :info, :string
    field :total_area, :string
    field :measurement, :string
    field :phase, :string
    field :site_number, :string
    field :community_id, :id
    field :user_id, :id

    timestamps()
  end

  @doc false
  def changeset(%Site{} = site, attrs) do
    site
    |> cast(attrs, [:site_number, :measurement, :direction_facing, :corner, :cross, :phase, :info, :total_area])
    |> validate_required([:site_number, :total_area, :cross, :phase])
  end
end

lib/smarthood_web/controllers/site_controller.ex
defmodule SmarthoodWeb.SiteController do
  use SmarthoodWeb, :controller

  alias Smarthood.Communities
  alias Smarthood.Communities.Site

  def index(conn, _params) do
    sites = Communities.list_sites()
    render(conn, "index.html", sites: sites)
  end

  def new(conn, _params) do
    changeset = Communities.change_site(%Site{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"site" => site_params}) do
    case Communities.create_site(site_params) do
      {:ok, site} ->
        conn
        |> put_flash(:info, "Site created successfully.")
        |> redirect(to: site_path(conn, :show, site))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    site = Communities.get_site!(id)
    render(conn, "show.html", site: site)
  end

  def edit(conn, %{"id" => id}) do
    site = Communities.get_site!(id)
    changeset = Communities.change_site(site)
    render(conn, "edit.html", site: site, changeset: changeset)
  end

  def update(conn, %{"id" => id, "site" => site_params}) do
    site = Communities.get_site!(id)

    case Communities.update_site(site, site_params) do
      {:ok, site} ->
        conn
        |> put_flash(:info, "Site updated successfully.")
        |> redirect(to: site_path(conn, :show, site))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", site: site, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    site = Communities.get_site!(id)
    {:ok, _site} = Communities.delete_site(site)

    conn
    |> put_flash(:info, "Site deleted successfully.")
    |> redirect(to: site_path(conn, :index))
  end
end

lib/smarthood_web/views/site_view.ex
defmodule SmarthoodWeb.SiteView do
  use SmarthoodWeb, :view
end

lib/smarthood_web/templates/site/edit.html.eex
<h4>Edit Site</h4>

<%= render "form.html", Map.put(assigns, :action, site_path(@conn, :update, @site)) %>

lib/smarthood_web/templates/site/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p><%= error_string_from_changeset(@changeset) %></p>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field col m2 s12">
      <%= label f, :site_number %>
      <%= text_input f, :site_number %>
      <%= error_tag f, :site_number %>
    </div>

    <div class="input-field col m3 s12">
      <%= label f, :measurement, "Measurement (in W x L)" %>
      <%= text_input f, :measurement %>
      <%= error_tag f, :measurement %>
    </div>

    <div class="input-field col m4 s12">
      <%= label f, :total_area, "Total Area (in sq.ft.)" %>
      <%= text_input f, :total_area , class: "autocomplete" %>
      <%= error_tag f, :total_area %>
    </div>

    <div class="form-control col m3 s12">
      <%= label f, :direction_facing %>
      <%= select(f, :direction_facing, ["Choose your option": "0", "North": "north", "East": "east", "South": "south", "West": "west"]) %>
      <%= error_tag f, :direction_facing %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col m2 s12">
      <%= label f, :cross, "Cross" %>
      <%= text_input f, :cross %>
      <%= error_tag f, :cross %>
    </div>

    <div class="input-field col m2 s12">
      <%= label f, :phase, "Phase" %>
      <%= text_input f, :phase %>
      <%= error_tag f, :phase %>
    </div>
    
    <div class="col m8 s12" style="margin-top: 25px;">
        <%= checkbox f, :corner, class: "filled-in center-align", id: "site_corner" %>
        <%= label f, :corner %>
        <%= error_tag f, :corner %>
    </div>

  </div>

  <div class="row">
    <div class="input-field col m12 s12">
      <%= label f, :info, "Other Information" %>
      <%= textarea f, :info, class: "materialize-textarea" %>
      <%= error_tag f, :info %>
    </div>
  </div>
    <%= hidden_input f, :community_id, value: get_active_user_community(@conn.assigns.current_user.id).id %>
    <%= hidden_input f, :user_id, value: @conn.assigns.current_user.id %>

  <div class="form-group">
    <%= submit "Submit", class: "btn waves-effect waves-light" %>
    <span><%= link "Back", to: site_path(@conn, :index), class: "waves-effect waves-light btn" %></span>
  </div>
<% end %>

<script>

  $(document).ready(function() {
    $('select option:nth(0)').prop("disabled","disabled");
    $('select').material_select();
  });
    

</script>

lib/smarthood_web/templates/site/index.html.eex
<span><%= link "Add Site", to: site_path(@conn, :new), class: "waves-effect waves-light btn" %></span>
<br>
<%= if length(@sites) > 0 do %>
<h4>Listing Sites</h4>

<table class="table">
  <thead>
    <tr>
      <th>Site number</th>
      <th>Measurement</th>
      <th>Direction facing</th>
      <th>Corner</th>
      <th>Cross</th>
      <th>Phase</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for site <- @sites do %>
    <tr>
      <td><%= site.site_number %></td>
      <td><%= site.measurement %></td>
      <td><%= site.direction_facing %></td>
      <td><%= site.corner %></td>
      <td><%= site.cross %></td>
      <td><%= site.phase %></td>

      <td class="text-right">
        <span><%= link "Show", to: site_path(@conn, :show, site), class: "waves-effect waves-light btn" %></span>
        <span><%= link "Edit", to: site_path(@conn, :edit, site), class: "waves-effect waves-light btn" %></span>
        <span><%= link "Delete", to: site_path(@conn, :delete, site), method: :delete, data: [confirm: "Are you sure?"], class: "waves-effect waves-light btn" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<br>
<% else %>
<h4 class="center">Add your sites</h4>
<% end %>

lib/smarthood_web/templates/site/new.html.eex
<h4>New Site</h4>

<%= render "form.html", Map.put(assigns, :action, site_path(@conn, :create)) %>

lib/smarthood_web/templates/site/show.html.eex
<h4>Show Site</h4>

<div class="row">
    <div class="input-field col m2 s12">
      <%= tag :input, type: "text", value: @site.site_number, class: "black-text", readonly: "readonly" %>
      <%= content_tag :label, :site_number, class: "active" %>
    </div>

    <div class="input-field col m3 s12">
      <%= tag :input, type: "text", value: @site.measurement, class: "black-text", readonly: "readonly" %>
      <%= content_tag :label, "Measurement (in W x L)" , class: "active"  %>
    </div>

    <div class="input-field col m4 s12">
      <%= tag :input, type: "text", value: @site.total_area, class: "black-text", readonly: "readonly" %>
      <%= content_tag :label, "Total Area (in sq.ft.)", class: "active" %>
    </div>

    <div class="input-field  col m3 s12">
      <%= tag :input, type: "text", value: @site.direction_facing, class: "black-text", readonly: "readonly" %>
      <%= content_tag :label, "Direction Facing", class: "active" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col m2 s12">
      <%= tag :input, type: "text", value: @site.cross, class: "black-text", readonly: "readonly" %>
      <%= content_tag :label, "Cross", class: "active" %>
    </div>

    <div class="input-field col m2 s12">
      <%= tag :input, type: "text", value: @site.phase, class: "black-text", readonly: "readonly" %>
      <%= content_tag :label, "Phase", class: "active" %>
    </div>
    
    <div class="input-field col m3 s12">
      <%= tag :input, type: "text", value: (if (@site.corner), do: "Yes", else: "No") , class: "black-text", readonly: "readonly" %>
      <%= content_tag :label, "Corner", class: "active" %>   
    </div>

  </div>

  <div class="row">
    <div class="input-field col m12 s12">
      <%= tag :input, type: "text", value: @site.info, class: "black-text", readonly: "readonly" %>
      <%= content_tag :label, "Other Information", class: "active" %>  
    </div>
  </div>




<span><%= link "Edit", to: site_path(@conn, :edit, @site), class: "waves-effect waves-light btn" %></span>
<span><%= link "Back", to: site_path(@conn, :index), class: "waves-effect waves-light btn"  %></span>
<span class="right"><%= link "Add House", to: site_house_path(@conn, :new, @site), class: "waves-effect waves-light btn"  %></span>