lib/smarthood_web/router.ex
defmodule SmarthoodWeb.Router do
  use SmarthoodWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Pjax.Plugs.Pjax)
  end

  # pipeline :browser_auth do
  #   plug Guardian.Plug.VerifySession
  #   plug Guardian.Plug.EnsureAuthenticated, handler: Smarthood.AuthErrorHandler
  #   plug Guardian.Plug.LoadResource, allow_blank: true
  #   plug Smarthood.CurrentUser
  # end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end
  pipeline :browser_session do
    plug(Smarthood.Guardian.AuthPipeline.Browser)
    plug(Smarthood.Auth.CurrentUser)
  end

  pipeline :login_required do
    plug(Smarthood.Guardian.AuthPipeline.Authenticate)
  end

  # pipeline :authorize_admin do
  #   plug Smarthood.Guardian.AuthPipeline.Authenticate
  #   plug Smarthood.Auth.Authorize, :admin
  # end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(Smarthood.Guardian.AuthPipeline.JSON)
  end

  scope "/auth", SmarthoodWeb do
    pipe_through([:browser, :browser_session])

    get("/:provider", AuthController, :new)
    get("/:provider/callback", AuthController, :callback)
    post("/identity/callback", AuthController, :identity_callback)
    delete("/delete", AuthController, :delete)
  end

  scope "/", SmarthoodWeb do
    pipe_through([:browser, :browser_session])

    resources("/users", UserController, only: [:new, :create])
  end

  scope "/", SmarthoodWeb do
    # Use the default browser stack
    pipe_through([:browser, :browser_session, :login_required])

    get("/", PageController, :index)
    resources("/users", UserController, except: [:new, :create])
    resources("/roles", RoleController)

    # resources "/organizations", OrganizationController do
    resources "/organizations", OrganizationController do
      resources("/domains", DomainController)
      resources("/work_status_types", WorkStatusTypeController)
      resources("/spreadsheets", SpreadsheetController)
      resources("/to_dos", ToDoController)
    end

    resources "/communities", CommunityController do
      resources("/users", UserController) do
        get("/join", UserController, :add_user_to_community, as: :join)
        get("/unjoin", UserController, :remove_user_from_community, as: :unjoin)
      end
    end
    resources "/sites", SiteController do
      resources "/houses", HouseController
    end

    resources "/houses", HouseController

    resources "/to_dos", ToDoController, only: [], as: :to_do do
      resources("/to_do_users", ToDoUserController, as: :users)
    end

    resources "/teams", TeamController do
      get("/add_users", TeamController, :add_users, as: :add_users)
      get("/remove_users", TeamController, :remove_users, as: :remove_users)
      get("/set_as_moderator", TeamController, :set_as_moderator, as: :set_as_moderator)
      get("/set_as_member", TeamController, :set_as_member, as: :set_as_member)
    end

    post("/photos/upload", PhotoController, :upload)

    resources "/work_statuses", WorkStatusController do
      resources("/key_result_areas", KeyResultAreaController)
      resources("/comments", CommentController)
    end

    get("/team_work_statuses", WorkStatusController, :team_work_statuses, as: :team_work_statuses)
    resources("/tasks", TaskController)

    get(
      "/export_to_do_to_tasks",
      TaskController,
      :export_to_do_to_tasks,
      as: :export_to_do_to_tasks
    )

    get("/team_to_dos", ToDoController, :team_to_dos, as: :team_to_dos)
  end

  # Other scopes may use custom stacks.
  # scope "/api", SmarthoodWeb do
  #   pipe_through :api
  # end
end

lib/smarthood/organizations/domain.ex
defmodule Smarthood.Organizations.Domain do
  use Ecto.Schema
  import Ecto.Changeset
  alias Smarthood.Organizations.{Domain, Organization}


  schema "domains" do
    field :name, :string
    belongs_to :organization, Organization

    timestamps()
  end

  @doc false
  def changeset(%Domain{} = domain, attrs) do
    domain
    |> cast(attrs, [:name, :organization_id])
    |> validate_required([:name])
    |> unique_constraint(:name)
  end
end

lib/smarthood_web/controllers/domain_controller.ex
defmodule SmarthoodWeb.DomainController do
  use SmarthoodWeb, :controller

  plug Smarthood.Plugs.DomainAuthorizer

  alias Smarthood.Organizations
  alias Smarthood.Organizations.Domain

  def index(conn, params) do
    org_id = params["organization_id"]
    org = Organizations.get_organization_with_domains!(org_id)
    domains = Organizations.list_domains(org_id)
    render(conn, "index.html", domains: domains, org: org)
  end

  def new(conn, params) do
    org = Organizations.get_organization_with_domains!(params["organization_id"])
    changeset = Organizations.change_domain(%Domain{})
    render(conn, "new.html", changeset: changeset, org: org)
  end

  def create(conn, %{"domain" => domain_params, "organization_id" => org_id}) do
    org = Organizations.get_organization_with_domains!(org_id)
    
    case Organizations.create_domain(domain_params, org) do
      {:ok, _domain} ->
        conn
        |> put_flash(:info, "Domain created successfully.")
        |> redirect(to: organization_domain_path(conn, :index, org_id))
       # |> redirect(to: organization_domain_path(conn, :show, org, domain))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, org: org)
    end
  end
      
  def show(conn, %{"organization_id" => org_id, "id" => id}) do
    domain = Organizations.get_domain!(id)
    render(conn, "show.html", domain: domain, org_id: org_id)
  end
      
  
  def edit(conn, %{"organization_id" => org_id, "id" => id}) do
    org = Organizations.get_organization_with_domains!(org_id)
    domain = Organizations.get_domain!(id)
    changeset = Organizations.change_domain(domain)
    render(conn, "edit.html", domain: domain, changeset: changeset, org: org)
  end

  def update(conn, %{"id" => id, "domain" => domain_params, "organization_id" => org_id}) do
    domain = Organizations.get_domain!(id)

    case Organizations.update_domain(domain, domain_params) do
      {:ok, domain} ->
        conn
        |> put_flash(:info, "Domain updated successfully.")
        |> redirect(to: organization_domain_path(conn, :show, org_id, domain))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", domain: domain, changeset: changeset, org_id: org_id)
    end
  end

  def delete(conn, %{"organization_id" => org_id, "id" => id}) do
    domain = Organizations.get_domain!(id)
    {:ok, _domain} = Organizations.delete_domain(domain)

    conn
    |> put_flash(:info, "Domain deleted successfully.")
    |> redirect(to: organization_domain_path(conn, :index, org_id))
  end
end

lib/smarthood_web/views/domain_view.ex
defmodule SmarthoodWeb.DomainView do
  use SmarthoodWeb, :view
end

lib/smarthood_web/templates/domain/edit.html.eex
<h4>Edit Domain</h4>
<h5>Organization: <%= @org.name %> </h5>
<br>

<%= form_for @changeset, organization_domain_path(@conn, :update, @org, @domain), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger red-text">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <span><%= submit "Submit", class: "btn btn-primary" %><span>
    <span><%= link "Back", to: organization_path(@conn, :show, @org), class: "btn" %></span>
  </div>
<% end %>

lib/smarthood_web/templates/domain/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger red-text">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/smarthood_web/templates/domain/index.html.eex
<h4>Domains</h4>

<h5>Organization: <%= @org.name %> </h5>
<br>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for domain <- @domains do %>
    <tr>
      <td><%= domain.name %></td>

      <td class="text-right">
        <span><%= link "Show", to: organization_domain_path(@conn, :show, @org, domain), class: "btn btn-default btn-xs hide" %></span>
        <span><%= link "Edit", to: organization_domain_path(@conn, :edit, @org, domain), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: organization_domain_path(@conn, :delete, @org, domain), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Domain", to: organization_domain_path(@conn, :new, @org), class: "btn" %></span>
<span><%= link "Back", to: organization_path(@conn, :show, @org), class: "btn" %></span>

lib/smarthood_web/templates/domain/new.html.eex
<h4>New Domain</h4>
<h5>Organization: <%= @org.name %> </h5>
<h6>Create domain to auto-validate Users's email id against organization.</h6>
<h6>e.g. smartzip.com, reach150.com, etc...</h6>
<br>
<%= form_for @changeset,  organization_domain_path(@conn, :create, @org), fn f -> %>
  <%= if @changeset.action do %>
    <div class="card red lighten-5" role="alert">
      <div class="card-content red-text">
        <p> Please check the errors below.</p>
      </div>
    </div>
  <% end %>

  <div class="input-field col s12">
  <i class="material-icons prefix">domain</i>
    <%= text_input f, :name, class: "validate" %>
    <%= label f, :name %>
    <%= error_tag f, :name %>
  </div>
 <%= hidden_input f, :organization_id, value: @org.id %>
  <div>
    <%= submit "Submit", class: "btn" %>
    <span><%= link "Back", to: organization_domain_path(@conn, :index, @org), class: "btn" %></span>
  </div>
<% end %>

lib/smarthood_web/templates/domain/show.html.eex
<h4>Show Domain</h4>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @domain.name %>
  </li>

</ul>

<span><%= link "Edit", to: organization_domain_path(@conn, :edit, @org_id, @domain), class: "btn" %></span>
<span><%= link "Back", to: organization_path(@conn, :show, @org_id), class: "btn" %></span>